# Generated by Django 2.2.2 on 2019-06-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cmdb',
            fields=[
                ('property_id', models.AutoField(primary_key=True, serialize=False)),
                ('property_name', models.CharField(max_length=64)),
                ('property_num', models.CharField(max_length=32)),
            ],
        ),
    ]
